[platformio]
src_dir = src

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_speed = 230400
monitor_speed = 74880

extra_scripts = pre:scripts/patch_zenoh_priority.py

lib_deps = https://github.com/eclipse-zenoh/zenoh-pico.git#1.9.0
build_flags =
    -DZENOH_ARDUINO_ESP32
    -DZENOH_GENERIC
    -DZ_TASK_PRIORITY=1
    -I"${PROJECT_DIR}/include"
